name: survos2_env_fc
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - addict
  - begins
  - blas
  - blosc
  - bokeh
  - brotli
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charls
  - click
  - cloudpickle
  - conda
  - coverage
  - cryptography
  - cudatoolkit
  - cudnn
  - cycler
  - cytoolz
  - cython
  - dask
  - dask-core
  - dask-image
  - decorator
  - distributed
  - enum34
  - expat
  - falcon
  - fontconfig
  - freetype
  - fsspec
  - giflib
  - glib
  - h5py
  - hdbscan
  - hdf5
  - heapdict
  - hug
  - icu
  - idna
  - imagecodecs
  - imagecodecs-lite
  - imageio
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - jxrlib
  - kiwisolver
  - lcms2
  - libaec
  - libffi
  - libllvm9
  - libpng
  - libtiff
  - libwebp
  - libxcb
  - libxml2
  - libzopfli
  - llvmlite
  - locket
  - loguru
  - lz4-c
  - magicgui
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msgpack-python
  - networkx
  - ninja
  - numba
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - packaging
  - pandas
  - paramiko
  - partd
  - pathlib
  - pcre
  - pillow
  - pims
  - pip
  - psutil
  - pycparser
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqtgraph
  - pysocks
  - python
  - python-dateutil
  - python-mimeparse
  - python-wget
  - python_abi
  - pytorch
  - pytz
  - pywavelets
  - pyyaml
  - qt
  - qtawesome
  - qtpy
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - slicerator
  - snappy
  - sortedcontainers
  - sqlite
  - tbb
  - tblib
  - threadpoolctl
  - tifffile
  - tk
  - toolz
  - torchvision
  - tornado
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - yaml
  - zict
  - zlib
  - zstd
  - pip:
    - alabaster
    - appdirs
    - attrdict
    - attrs
    - babel
    - backcall
    - cachey
    - cuda-slic
    - docutils
    - freetype-py
    - humanize
    - imagesize
    - importlib-metadata
    - iniconfig
    - ipykernel
    - ipython
    - ipython-genutils
    - jedi
    - jupyter-client
    - jupyter-core
    - kornia
    - mako
    - more-itertools
    - morphsnakes
    - mrcfile
    - napari
    - napari-plugin-engine
    - napari-svg
    - nibabel
    - nose
    - numpydoc
    - parse
    - parso
    - pexpect
    - pickleshare
    - pluggy
    - prompt-toolkit
    - ptyprocess
    - py
    - pycuda
    - pydantic
    - pygments
    - pyopengl
    - pytest
    - python-deprecated
    - pytools
    - pyzmq
    - qtconsole
    - simpleitk
    - snowballstemmer
    - sphinx
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - tensorly
    - toml
    - torchio
    - tqdm
    - traitlets
    - vispy
    - wcwidth
    - wget
    - wrapt
    - zipp

